# Generated by Django 6.0.1 on 2026-02-09 01:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videogames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(max_length=100)),
                ('favorite_video_game', models.CharField(max_length=200)),
                ('level_of_difficulty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('fighting_a_feature', models.BooleanField(default=False)),
            ],
        ),
    ]
