# Generated by Django 6.0.1 on 2026-02-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogames',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
