# Generated by Django 6.0.1 on 2026-02-23 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_videogames_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('headquarters', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='videogames',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='videogames', to='main.genre'),
        ),
        migrations.AddField(
            model_name='videogames',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.publisher'),
        ),
        migrations.CreateModel(
            name='VideogameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('platform_notes', models.TextField(blank=True)),
                ('videogame', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='main.videogames')),
            ],
        ),
    ]
