# Generated by Django 6.0.1 on 2026-03-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_feedback_submitted_at_alter_feedback_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_uploads/'),
        ),
    ]
