# Generated by Django 6.0.1 on 2026-04-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_feedback_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogames',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
